# Generated by Django 5.0.6 on 2024-06-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleElon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlovha')),
                ('body', models.TextField(verbose_name='Tana qismi')),
                ('img', models.ImageField(upload_to='Photos/Yangiliklar/')),
                ('img1', models.ImageField(blank=True, upload_to='Photos/Yangiliklar/')),
                ('img2', models.ImageField(blank=True, upload_to='Photos/Yangiliklar/')),
                ('img3', models.ImageField(blank=True, upload_to='Photos/Yangiliklar/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Elon',
                'verbose_name_plural': 'Elonlar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleKafedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kafedra nomi')),
                ('name', models.CharField(max_length=200, verbose_name='Kafedra mudiri FISH')),
                ('img', models.ImageField(upload_to='Photos/Yangiliklar/')),
                ('qabul', models.CharField(max_length=200, verbose_name='qabul vaqti')),
                ('telRaqam', models.CharField(max_length=200, verbose_name='Raqami')),
                ('mail', models.EmailField(max_length=254, verbose_name='email')),
                ('text', models.TextField(verbose_name='batafsil')),
                ('img1', models.ImageField(upload_to='Photos/Yangiliklar/', verbose_name='kafedra rasmi-1')),
                ('img2', models.ImageField(upload_to='Photos/Yangiliklar/', verbose_name='kafedra rasmi-2')),
            ],
            options={
                'verbose_name': 'Kafedra',
                'verbose_name_plural': 'Kafedralar',
            },
        ),
        migrations.CreateModel(
            name='ArticleNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlovha')),
                ('body', models.TextField(verbose_name='Tana qismi')),
                ('img', models.ImageField(upload_to='Photos/Yangiliklar/')),
                ('img1', models.ImageField(blank=True, upload_to='Photos/Yangiliklar/')),
                ('img2', models.ImageField(blank=True, upload_to='Photos/Yangiliklar/')),
                ('img3', models.ImageField(blank=True, upload_to='Photos/Yangiliklar/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ekranImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='Photos/ekran_IMG/')),
            ],
            options={
                'verbose_name': 'Ekran Rasmi',
                'verbose_name_plural': 'Ekran Rasmlari',
            },
        ),
    ]
